export const defaultServiceContractantDashboardDict = {
  header: {
    title: "Tableau de Bord",
    subtitle:
      "Gerez vos procedures de commande publique en toute transparence.",
    createButton: "Creer une Nouvelle AO",
    notifications: "Notifications",
    logout: "Se deconnecter",
  },
  summary: {
    activeAos: "AOs Actifs",
    pendingAttributions: "Attributions en attente",
    openRecours: "Recours ouverts",
    ongoingMarches: "Marches en cours",
  },
  quickActions: {
    title: "Actions Rapides",
    createAo: "Nouvel AO",
    myAos: "Mes AO",
    commissions: "Commissions",
  },
  recentActivity: {
    title: "Activite Recente",
    viewAll: "Voir tout",
    empty: "Aucune activite recente.",
  },
  alerts: {
    title: "Alertes IA Al-Mizan",
    empty: "Aucune alerte en cours.",
    deadlinesTitle: "Echeances prochaines (48h)",
  },
  support: {
    title: "Support & Guide",
    guide: "Guide des procedures 2024",
    contact: "Contacter le support technique",
  },
  errorLoading: "Impossible de charger les donnees du tableau de bord.",
};

export type ServiceContractantDashboardDict =
  typeof defaultServiceContractantDashboardDict;

export const defaultTendersListDict = {
  title: "Mes Appels d'Offres",
  createBtn: "Creer une Nouvelle AO",
  searchPlaceholder: "Rechercher par reference ou objet...",
  searchLabel: "Recherche",
  filterByStatus: "Filtrer par statut",
  filters: {
    status: "Statut",
    all: "Tous",
    draft: "Brouillon",
    published: "Publie",
    ongoing: "En cours",
    evaluation: "Evaluation",
    awarded: "Attribue",
    cancelled: "Annule",
    dateStart: "Date debut",
    dateEnd: "Date fin",
    reset: "Reinitialiser",
    searchLabel: "Recherche",
    filterByStatus: "Filtrer par statut",
  },
  table: {
    reference: "Reference",
    object: "Objet",
    type: "Type",
    deadline: "Date limite depot",
    status: "Statut",
    actions: "Actions",
  },
  actions: {
    view: "Voir les details",
    edit: "Modifier",
    changeStatus: "Changer le statut",
    delete: "Supprimer",
  },
  empty: "Aucun appel d'offres trouve.",
  types: {
    open: "Ouvert",
    restricted: "Restreint",
    direct: "Gre a gre",
  },
  pagination: {
    showing: "Affichage de",
    to: "a",
    of: "sur",
    entries: "entrees",
    previous: "Precedent",
    next: "Suivant",
  },
  confirmDelete: "Voulez-vous vraiment supprimer cet appel d'offres ?",
  aoCreation: {
    createTitle: "Creer un Appel d'Offres",
    currency: "DZD",
    stepPrefix: "Etape",
    stepOn: "sur",
    stepTitles: [
      "Informations Generales",
      "Lots",
      "CDC",
      "Eligibilite",
      "Evaluation",
      "Revision et Publication",
    ],
    buttons: {
      next: "Etape suivante",
      back: "Retour",
      saveDraft: "Enregistrer en brouillon",
      saveAsDraft: "Sauvegarder en brouillon",
      publishAo: "Publier AO",
      publishCdc: "Publier CDC",
      uploadFile: "Upload fichier",
      replaceFile: "Remplacer le fichier",
      downloadCdc: "Telecharger CDC",
      edit: "Modifier",
      cancel: "Annuler",
    },
    review: {
      title: "Etape 6: Revision et Publication",
      subtitle: "Verification finale des informations avant publication.",
      validationChecks: "Controles de validation",
      generalInfo: "Informations generales",
      statusPublished: "Publie",
      statusUnpublished: "Non publie",
    },
    messages: {
      draftSaved: "Brouillon enregistre avec succes.",
      publishBlockedPrefix: "Impossible de publier:",
      publishSuccessPrefix: "AO publie avec succes. Avis genere:",
    },
    header: {
      breadcrumbDashboard: "Tableau de bord",
      breadcrumbAo: "Appels d'offres",
      editModeLabel: "Edition du brouillon AO en cours.",
      progression: "Progression",
    },
    step6: {
      reviewLabels: {
        aoName: "Nom de l'AO",
        category: "Categorie",
        duration: "Duree d'execution",
        estimatedValue: "Valeur estimee",
      },
      lotsTitle: "Structure des Lots",
      lotsColumns: {
        lotId: "ID Lot",
        description: "Designation",
        quantityDelay: "Quantite / Delai",
      },
      lotsEmpty: "Aucun lot defini.",
      scoringTitle: "Criteres d'Evaluation",
      scoringEmpty: "Aucun critere de notation.",
      totalWeighting: "Ponderation Totale",
      eligibilityTitle: "Criteres d'Eligibilite",
      eligibilityCriteria: "criteres",
      eliminatoryRules: "regles eliminatoires actives.",
      checks: {
        generalInfoTitle: "Informations Generales",
        generalInfoDesc: "Reference, objet et description",
        lotsTitle: "Details des Lots",
        lotsDesc: "Au moins un lot configure",
        cdcTitle: "Cahier des Charges",
        cdcDesc: "Document CDC telecharge",
        weightTitle: "Ponderation",
        weightDesc: "Total doit etre 100%",
        datesTitle: "Coherence des Dates",
        datesDesc: "Chronologie des echeances",
        eligibilityTitle: "Eligibilite",
        eligibilityDesc: "Criteres d'acces definis",
      },
      cdcDocTitle: "Document du CDC",
      cdcNoFile: "Aucun fichier telecharge.",
      versionLabel: "Version: ",
      avisGenerated: "Avis genere",
    },
    validation: {
      required: "Champ obligatoire",
      pdfOnly: "Seuls les fichiers PDF sont autorises",
      cdcFileRequired: "Veuillez telecharger le fichier CDC",
      addEvaluationCriterion: "Ajoutez au moins un critere d'evaluation.",
      totalWeightMustBe100:
        "La somme totale des ponderations doit etre egale a 100%.",
      weightingInvalid: "Valeur invalide (0 < % <= 100)",
      eliminationScoreRange: "Doit etre entre 0 et 100",
      offerDeadlineAfterDce: "Doit etre apres la date DCE",
      openingDateAfterOffer: "Doit etre apres la date limite depot",
      fileTooLarge: "Le fichier ne doit pas depasser 25 MB",
    },
    errors: {
      draftSaveFailed: "Echec de sauvegarde du brouillon.",
      publishFailed: "Echec de publication de l'AO.",
    },
    footer: "Besoin d'aide ? • Centre de l'assistant",
  },
};

export type TendersListDict = typeof defaultTendersListDict;
